routes/web.php
<?php
use App\Htttp\Middleware\CheckRole;


Route::get('/', function () {
    return view('frontpage.main.index');
})->name('home.index');
Route::get('/news','FrontPage\Admin\BlogController@index')->name('news');
Route::get('/news/{slug}','FrontPage\Admin\BlogController@show')->name('news.show');

Route::get('web/{uuid}','FrontPage\Takmir\WebPageController@index')->name('web');

Auth::routes();
Auth::routes(['verify' => true]);

Route::group(['middleware'=>['auth','verified']], function () {
    Route::get('test',function(){
        return view('dashboard.takmir.organization.organization');
    });
    Route::get('/home', 'HomeController@index')->name('home');

    // Blog
    Route::resource('blog','Dashboard\BlogController');
    Route::get('api.blog','Dashboard\BlogController@blogApi')->name('api.blog');

    // Jamah
    Route::resource('jamaah', 'Dashboard\Takmir\JamaahController');
    Route::get('api.jamaah', 'Dashboard\Takmir\JamaahController@jamaahApi')->name('api.jamaah');

    // Organization Start
    Route::get('org/{uuid}','Dashboard\Takmir\OrganizationController@index')->name('org');
    
    Route::get('org/{uuid}/edit','Dashboard\Takmir\OrganizationController@editStructure')->name('org.edit');
    Route::PATCH('org/{uuid}/update','Dashboard\Takmir\OrganizationController@updateStructure')->name('org.update');

    Route::get('org/job/{uuid}/edit','Dashboard\Takmir\OrganizationController@editJobdesc')->name('org.editjob');
    Route::PATCH('org/job/{uuid}/update','Dashboard\Takmir\OrganizationController@updateJobdesc')->name('org.updatejob');
    // Organization End

    // Profile
    Route::get('profile','Dashboard\Takmir\ProfileController@index')->name('profile');
    Route::get('profile/edit/{uuid}','Dashboard\Takmir\ProfileController@edit')->name('profile.edit');
    Route::PATCH('profile/update/{id}','Dashboard\Takmir\ProfileController@update')->name('profile.update');
    Route::get('profile/passEdit/{uuid}','Dashboard\Takmir\ProfileController@passEdit')->name('profile.passEdit');
    Route::PATCH('profile/passUpdate/{uuid}','Dashboard\Takmir\ProfileController@passUpdate')->name('profile.passUpdate');


    Route::resource('takmir', 'Dashboard\Admin\User\TakmirController');

    Route::group(['middleware' => ['role:admin']], function () {

        Route::get('api.takmir', 'Dashboard\Admin\User\TakmirController@takmirApi')->name('api.takmir');

        Route::resource('admin', 'Dashboard\Admin\User\AdminController');
        Route::get('api.admin', 'Dashboard\Admin\User\AdminController@adminApi')->name('api.admin');

    });
});

app/Models/Jamaah.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Jamaah extends Model
{
    protected $guarded = ['id'];
    protected $table = 'jamaahs';

    public function masjid(){
        return $this->belongsTo('App\Models\Takmir');
    }
}

app/Models/Takmir.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Takmir extends Model
{
    protected $guarded = ['id'];
    protected $table = 'takmirs';

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function mosque(){
        return $this->hasOne('App\Models\Mosque','takmir_id');
    }

    public function jamaah(){
        return $this->hasMany('App\Models\Jamaah','takmir_id');
    }

    public function oragnization(){
        return $this->hasOne('App\Models\Organization','takmir_id');
    }

    public function jobdesc(){
        return $this->hasOne('App\Models\JobdescOrg','takmir_id');
    }
}

app/Http/Controllers/Dashboard/Admin/User/TakmirController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\User;

use Ramsey\Uuid\Uuid;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\DB;
use App\Models\UserRole;
use App\Models\Takmir;
use App\Models\Admin;
use App\Models\Mosque;
use App\Models\Organization;
use App\Models\JobdescOrg;

class TakmirController extends Controller
{

    public function index()
    {
        return view('dashboard.admin.user.takmir.all_user');        
    }

    
    public function create()
    {
        return view('dashboard.admin.user.takmir.add_user');
    }
    
    public function store(Request $request)
    {
        $user = new User;
        $takmir = new Takmir;
        $mosque = new Mosque;
        $org = new Organization;
        $jobdesc = new JobdescOrg;

        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required|unique:users',
            'password' => 'required|min:8'
        ]);
        
        $user->uuid = Uuid::uuid4();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

        switch ($request->role) {
            case 3:
                $takmir->user_id = $user->id;
                $takmir->save();

                $mosque->takmir_id = $takmir->id;
                $mosque->save();

                $org->takmir_id = $takmir->id;
                $org->save();

                $jobdesc->takmir_id = $takmir->id;
                $jobdesc->save();
                // dd($mosque);

                UserRole::create(['user_id' => $user->id,'role_id' => 3]);
                break;
            case 2:
                Admin::create(['user_id'=>$user->id]);
                UserRole::create(['user_id' => $user->id,'role_id' => 3]);
                UserRole::create(['user_id' => $user->id,'role_id' => 2]);
                break;
        }

        return redirect()->route('takmir.index')->with('success','Berhasil Menambahkan'); 
    }

    
    public function show($id)
    {
        $user = User::where('uuid',$id)->first();
        $takmir = $user->takmir()->first();
        $mosque = $takmir->mosque()->first();

        // dd($mosque);

        return view('dashboard.admin.user.takmir.detail_user',compact('user','takmir','mosque'));
    }
    
    public function edit($id)
    {
        $user = User::where('uuid',$id)->first();
        $takmir = $user->takmir()->first();
        $mosque = $takmir->mosque()->first();
        // dd($takmir);

        return view('dashboard.admin.user.takmir.edit_user',compact('user','takmir','mosque'));
    }
    
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required',
            'password' => 'required|min:8'
        ]);
        
        $user = User::where('uuid',$id)->first();
        // dd($user);
        $takmir = $user->takmir()->first();
        $mosque = $takmir->mosque()->first();

        //============ User =========
        $user->name = $request->name;
        $user->email = $request->email;

        if ($request->password != $user->password) {
            $user->password = bcrypt($request->password);
        }
        $user->save();

        //=========== Takmir =============
        $takmir->province = $request->province;
        $takmir->address = $request->address;
        $takmir->hp = $request->hp;
        $takmir->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $takmir->birth_place = $request->birth_place;
        $takmir->gender = $request->gender;

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/user',$photoName);
            $takmir->photo = $photoName;
        }
        $takmir->save();

        // ============ Mosque ===========
        $mosque->name = $request->mname;
        $mosque->province = $request->mprovince;
        $mosque->address = $request->maddress;
        $mosque->desc = $request->mdesc;

        if ($request->hasFile('mphoto')) {
            $photo = $request->file('mphoto');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/mosque',$photoName);
            $mosque->photo = $photoName;
        }

        $mosque->save();


        return redirect()->back()->with('success','Edit Success');
    }
    
    public function destroy($id)
    {
        $takmir = Takmir::find($id);
        
        $user = User::where('id',$takmir->user_id)->first();
        $user->delete();
    }

    public function takmirApi(){
        $user = DB::table('users')->rightJoin('takmirs','takmirs.user_id','=','users.id');

        return $this->displayTakmir($user);
    }
}

app/Http/Controllers/Dashboard/Takmir/Finance/CreditController.php
<?php

namespace App\Http\Controllers\Dashboard\Takmir\Finance;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CreditController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/Takmir/Finance/DebetController.php
<?php

namespace App\Http\Controllers\Dashboard\Takmir\Finance;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DebetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/Takmir/GallerytionController.php
<?php

namespace App\Http\Controllers\Dashboard\Takmir;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GallerytionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/Takmir/JamaahController.php
<?php

namespace App\Http\Controllers\Dashboard\Takmir;

use Ramsey\Uuid\Uuid;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Jamaah;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Models\Takmir;

class JamaahController extends Controller
{
    public function index()
    {
        return view('dashboard.takmir.jamaah.all_user');        
    }

    
    public function create()
    {
        return view('dashboard.takmir.jamaah.add_user');
    }
    
    public function store(Request $request)
    {
        $takmir = DB::table('takmirs')->where('user_id',Auth::user()->id)->first();
        $jamaah = new Jamaah;

        $request->validate([
            'photo' => 'image|mimes:jpeg,png,jpg',
        ]);
        
        $jamaah->uuid = Uuid::uuid4();
        $jamaah->takmir_id = $takmir->id;
        $jamaah->name = $request->name;
        $jamaah->address = $request->address;
        $jamaah->province = $request->province;
        $jamaah->hp = $request->hp;
        $jamaah->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $jamaah->birth_place = $request->birth_place;
        $jamaah->gender = $request->gender;
        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $photoName = $jamaah->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/jamaah',$photoName);
            $jamaah->photo = $photoName;
        }

        $jamaah->save();

        return redirect()->route('jamaah.index')->with('success','Berhasil Menambahkan'); 
    }

    
    public function show($id)
    {
        $jamaah = Jamaah::where('uuid',$id)->first();

        // dd($mosque);

        return view('dashboard.takmir.jamaah.detail_user',compact('jamaah'));
    }
    
    public function edit($id)
    {
        $jamaah = Jamaah::where('uuid',$id)->first();

        // dd($mosque);

        return view('dashboard.takmir.jamaah.edit_user',compact('jamaah'));
    }
    
    public function update(Request $request, $id)
    {
        
        $jamaah = Jamaah::where('uuid',$id)->first();

        //============ User =========
        $jamaah->name = $request->name;
        $jamaah->province = $request->province;
        $jamaah->address = $request->address;
        $jamaah->hp = $request->hp;
        $jamaah->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $jamaah->birth_place = $request->birth_place;
        $jamaah->gender = $request->gender;

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $photoName = $jamaah->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/jamaah',$photoName);
            $jamaah->photo = $photoName;
        }
        $jamaah->save();


        return redirect()->back()->with('success','Berhasil Menyimpan Perubahan');
    }
    
    public function destroy($id)
    {
        $jamaah = Jamaah::where('id',$id)->first();
        $jamaah->delete();

        // return redirect()->route('user.index')->with('danger','Berhasil Menghapus');
    }

    public function jamaahApi(){
        $takmir = DB::table('takmirs')->where('user_id',Auth::user()->id)->first();
        $jamaah = DB::table('jamaahs')->where('takmir_id',$takmir->id)->get();

        return $this->displayJamaah($jamaah);
    }
}

app/Http/Controllers/FrontPage/Takmir/WebPageController.php
<?php

namespace App\Http\Controllers\FrontPage\Takmir;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Takmir;
use App\User;
use App\Models\Organization;
use App\Models\JobdescOrg;
use App\Models\Mosque;

class WebPageController extends Controller
{
    public function index($uuid)
    {
        $user = User::where('uuid',$uuid)->first();
        $takmir = Takmir::where('user_id',$user->id)->first();
        $org = Organization::where('takmir_id',$takmir->id)->first();
        $job = JobdescOrg::where('takmir_id',$takmir->id)->first();
        $mosque = Mosque::where('takmir_id',$takmir->id)->first();
        $data = [
            'user' =>$user,
            'takmir'=> $takmir,
            'org' => $org,
            'job' => $job,
            'mosque' => $mosque
        ];

        return view('frontpage.takmir.index',compact('data'));
    }
}

resources/views/dashboard/takmir/jamaah/add_user.blade.php
@extends('dashboard.master')
@section('title')
Tambah Jamaah
@endsection
@section('content')
<div class="row">
    @include('layouts.patrials.alerts')
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Tambah Jamaah</h2>
                <form class="form-sample" method="POST" action="{{route('jamaah.store')}}"
                    enctype="multipart/form-data">
                    {{csrf_field()}} {{ method_field('POST')}}

                    {{-- Personal Info --}}
                    <div class="row">
                        <div class="col-md-3">
                            <img class="img-thumbnail d-block" src="{{asset('img/flower.jpg')}}" id='img-upload' alt="">
                            <br>
                            <div class="input-group upload">
                                <label class="btn btn-outline-primary shadow" for="photo">Upload Foto</label>
                                <input class="form-control d-none" value="{{ old('photo') }}"
                                    accept="image/jpeg,image/jpg,image/png," type="file" name="photo" id="photo">
                                <span class="errorval errorRegis" id="error_photo"></span>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Nama</label>
                                        <div class="col-sm-9">
                                            <input value="{{ old('name') }}" name="name" id="name" type="text"
                                                class="form-control">
                                            @error('name')
                                            <span class="mt-1 alert-danger" role="alert">
                                                <small>{{ $message }}</small>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Handphone</label>
                                        <div class="col-sm-9">
                                            <input value="{{ old('hp') }}" name="hp" id="hp" type="text"
                                                class="form-control">
                                            @error('hp')
                                            <span class="mt-1 alert-danger" role="alert">
                                                <small>{{ $message }}</small>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Jenis Kelamin</label>
                                        <div class="col-sm-9">
                                            <select name="gender" class="form-control">
                                                <option value="Pria"> Pria </option>
                                                <option value="Wanita"> Wanita </option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Tanggal Lahir</label>
                                        <div class="col-sm-9">
                                            <input value="{{ old('birth_date') }}" style="cursor:pointer" readonly
                                                name="birth_date" id="datepicker" class="form-control"
                                                placeholder="dd-mm-yyyy">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Tempat Lahir</label>
                                        <div class="col-sm-9">
                                            <input value="{{ old('birth_place') }}" name="birth_place" id="birth_place"
                                                class="form-control" placeholder="Jakarta">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label" for="province">Provinsi</label>
                                        <div class="col-sm-9">
                                            <select class="form-control" name="province" id="province">
                                                <option> </option>
                                                <option value="Jakarta">Jakarta</option>
                                                <option value="Aceh">Aceh</option>
                                                <option value="Bali">Bali</option>
                                                <option value="Banten">Banten</option>
                                                <option value="Bengkulu">Bengkulu</option>
                                                <option value="Gorontalo">Gorontalo</option>
                                                <option value="Jambi">Jambi</option>
                                                <option value="Jawa Barat">Jawa Barat</option>
                                                <option value="Jawa Tengah">Jawa Tengah</option>
                                                <option value="Jawa Timur">Jawa Timur</option>
                                                <option value="Kalimantan Barat">Kalimantan Barat</option>
                                                <option value="Kalimantan Selatan">Kalimantan Selatan</option>
                                                <option value="Kalimantan Tengah">Kalimantan Tengah</option>
                                                <option value="Kalimantan Timur">Kalimantan Timur</option>
                                                <option value="Kalimantan Utara">Kalimantan Utara</option>
                                                <option value="Kepulauan Bangka Belitung">Kepulauan Bangka Belitung</option>
                                                <option value="Kepulauan Riau">Kepulauan Riau</option>
                                                <option value="Lampung">Lampung</option>
                                                <option value="Maluku">Maluku</option>
                                                <option value="Maluku Utara">Maluku Utara</option>
                                                <option value="Nusa Tenggara Barat">Nusa Tenggara Barat</option>
                                                <option value="Nusa Tenggara Timur">Nusa Tenggara Timur</option>
                                                <option value="Papua">Papua</option>
                                                <option value="Papua Barat">Papua Barat</option>
                                                <option value="Riau">Riau</option>
                                                <option value="Sulawesi Barat">Sulawesi Barat</option>
                                                <option value="Sulawesi Selatan">Sulawesi Selatan</option>
                                                <option value="Sulawesi Tengah">Sulawesi Tengah</option>
                                                <option value="Sulawesi Tenggara">Sulawesi Tenggara</option>
                                                <option value="Sulawesi Utara">Sulawesi Utara</option>
                                                <option value="Sumatera Barat">Sumatera Barat</option>
                                                <option value="Sumatera Selatan">Sumatera Selatan</option>
                                                <option value="Sumatera Utara">Sumatera Utara</option>
                                                <option value="Yogyakarta">Yogyakarta</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group row">
                                        <label class="col-sm-3 col-form-label">Alamat</label>
                                        <div class="col-sm-9">
                                            <textarea name="address" type="text"
                                                class="form-control">{{old('address')}}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="submit" class="btn btn-primary btn-block" value="Simpan">
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script src="{{asset('js/jquery-1.12.4.js')}}"></script>
<script src="{{asset('js/jquery-ui.js')}}"></script>
@endsection

resources/views/dashboard/takmir/jamaah/all_user.blade.php
@extends('dashboard.master')
@section('title')
Semua Jamaah
@endsection
@section('content')
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                @include('layouts.patrials.alerts')
                <div class="row">
                    <div class="col-md-6"><h4 class="card-title"> Semua Jamaah </h4></div>
                    <div class="col-md-6"><a class="btn btn-success float-right" href="{{route('jamaah.create')}}">Tambah Jamaah</a></div>
                </div>
                <div class="center-pos" id="loadingDiv">
                        <img class="loading" src="{{asset('img/loading.gif')}}">
                </div>
                <div class="table-responsive">
                    <table id="table-admin" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Nama</th>
                                <th>Telepon</th>
                                <th>Gender</th>
                                <th>Provinsi</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script type="text/javascript">
    
    var ajaxApi = '{{route("api.jamaah")}}'
    var table = $('#table-admin').DataTable({
        order: [[1,'desc']],
        processing: true,
        serverSide: true,
        ajax : ajaxApi,
        columns : [
            {data: 'name', name: 'name'},
            {data: 'hp', name: 'hp'},
            {data: 'gender', name: 'gender'},
            {data: 'province', name: 'province'},
            {data: 'action', name: 'action',ordertable: false, searchable:false},
        ]

    })

    
    

    // Delete Data
    function deleteUser(id){
        // alert('bismillah');
        
        var csrf_token = $('meta[name="csrf-token"]').attr('content');

        Swal.fire({
          title: 'Kamu yakin ?',
          text: "User yang di hapus tidak akan kembali!",
          type: 'warning',
          showCancelButton: true,
          cancelButtonColor: '#d33',
          confirmButtonColor: '#3085d6',
          confirmButtonText: 'Ya, Hapus ini!'
        }).then((result) => {
        if (result.value) {
          $.ajax({
            url: "{{ url('jamaah') }}" + '/' + id,
            type: "DELETE",
            data: {'_method' : 'DELETE', '_token' : csrf_token},
            success: function(data){
              table.ajax.reload();
              Swal.fire({
                title:'Berhasil',
                text: 'User Sudah di hapus',
                type: 'success',
                timer: '1500'
              })
            },
            error: function(){
              Swal.fire({
                title: 'Oops',
                text: 'Something went wrong',
                type: 'error',
                timer: '1500'
              })
            }
          })
        }
      })
    }
    </script>
@endsection