routes/web.php
<?php
use App\Htttp\Middleware\CheckRole;


Route::get('/', function () {
    return view('frontpage.main.index');
})->name('home.index');
Route::get('/news','FrontPage\Admin\BlogController@index')->name('news');
Route::get('/news/{slug}','FrontPage\Admin\BlogController@show')->name('news.show');

Route::get('web/{uuid}','FrontPage\Takmir\WebPageController@index')->name('web');

Auth::routes();
Auth::routes(['verify' => true]);

Route::group(['middleware'=>['auth','verified']], function () {
    Route::get('test',function(){
        return view('dashboard.takmir.organization.organization');
    });
    Route::get('/home', 'HomeController@index')->name('home');

    // Blog
    Route::resource('blog','Dashboard\BlogController');
    Route::get('api.blog','Dashboard\BlogController@blogApi')->name('api.blog');

    // Jamah
    Route::resource('jamaah', 'Dashboard\Takmir\JamaahController');
    Route::get('api.jamaah', 'Dashboard\Takmir\JamaahController@jamaahApi')->name('api.jamaah');

    // Organization Start
    Route::get('org/{uuid}','Dashboard\Takmir\OrganizationController@index')->name('org');
    
    Route::get('org/{uuid}/edit','Dashboard\Takmir\OrganizationController@editStructure')->name('org.edit');
    Route::PATCH('org/{uuid}/update','Dashboard\Takmir\OrganizationController@updateStructure')->name('org.update');

    Route::get('org/job/{uuid}/edit','Dashboard\Takmir\OrganizationController@editJobdesc')->name('org.editjob');
    Route::PATCH('org/job/{uuid}/update','Dashboard\Takmir\OrganizationController@updateJobdesc')->name('org.updatejob');
    // Organization End

    // Profile
    Route::get('profile','Dashboard\Takmir\ProfileController@index')->name('profile');
    Route::get('profile/edit/{uuid}','Dashboard\Takmir\ProfileController@edit')->name('profile.edit');
    Route::PATCH('profile/update/{id}','Dashboard\Takmir\ProfileController@update')->name('profile.update');
    Route::get('profile/passEdit/{uuid}','Dashboard\Takmir\ProfileController@passEdit')->name('profile.passEdit');
    Route::PATCH('profile/passUpdate/{uuid}','Dashboard\Takmir\ProfileController@passUpdate')->name('profile.passUpdate');


    Route::resource('takmir', 'Dashboard\Admin\User\TakmirController');

    Route::group(['middleware' => ['role:admin']], function () {

        Route::get('api.takmir', 'Dashboard\Admin\User\TakmirController@takmirApi')->name('api.takmir');

        Route::resource('admin', 'Dashboard\Admin\User\AdminController');
        Route::get('api.admin', 'Dashboard\Admin\User\AdminController@adminApi')->name('api.admin');

    });
});

app/User.php
<?php
namespace App;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];
    protected $table = 'users';

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles(){
        return $this->belongsToMany('App\Models\Role', 'user_roles', 'user_id','role_id');
    }

    public function hasRole($role){
        if ($this->roles()->where('name',$role)->first()) {
            return true;
        }
        return false;
    }

    public function takmir(){
        return $this->hasOne('App\Models\Takmir');
    }

    public function admin(){
        return $this->hasOne('App\Models\Admin');
    }

    public function blog(){
        return $this->hasMay('App\Models\Blog');
    }
}

app/Http/Controllers/Dashboard/Admin/User/AdminController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\User;

use Ramsey\Uuid\Uuid;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\DB;
use App\Models\UserRole;
use App\Models\Admin;

class AdminController extends Controller
{
    public function index()
    {
        return view('dashboard.admin.user.admin.all_user');        
    }

    
    public function create()
    {
        return view('dashboard.admin.user.admin.add_user');
    }
    
    public function store(Request $request)
    {
        $user = new User;

        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required|unique:users',
            'password' => 'required|min:8'
        ]);
        
        $user->uuid = Uuid::uuid4();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

        Admin::create(['user_id'=>$user->id]);
        UserRole::create(['user_id' => $user->id,'role_id' => 3]);
        UserRole::create(['user_id' => $user->id,'role_id' => 2]);

        return redirect()->route('admin.index')->with('success','Berhasil Menambahkan'); 
    }

    
    public function show($id)
    {
        $user = User::where('uuid',$id)->first();
        $admin = $user->admin()->first();

        return view('dashboard.admin.user.admin.detail_user',compact('user','admin'));
    }
    
    public function edit($id)
    {
        $user = User::where('uuid',$id)->first();
        $admin = $user->admin()->first();

        return view('dashboard.admin.user.admin.edit_user',compact('user','admin'));
    }
    
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required',
            'password' => 'required|min:8'
        ]);
        
        $user = User::where('uuid',$id)->first();
        $admin = $user->admin()->first();

        //============ User =========
        $user->name = $request->name;
        $user->email = $request->email;

        if ($request->password != $user->password) {
            $user->password = bcrypt($request->password);
        }
        $user->save();

        //=========== admin =============
        $admin->province = $request->province;
        $admin->address = $request->address;
        $admin->hp = $request->hp;
        $admin->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $admin->birth_place = $request->birth_place;
        $admin->gender = $request->gender;

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/user',$photoName);
            $admin->photo = $photoName;
        }
        $admin->save();

        return redirect()->back()->with('success','Edit Success');
    }
    
    public function destroy($id)
    {
        $admin = Admin::find($id);
        $user = User::where('id',$admin->user_id)->first();
        // dd($user);

        $user->delete();
    }

    public function adminApi(){
        $user = DB::table('users')->rightJoin('admins','admins.user_id','=','users.id');

        return $this->displayAdmin($user);
    }
}

app/Http/Controllers/Dashboard/Admin/User/TakmirController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\User;

use Ramsey\Uuid\Uuid;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\DB;
use App\Models\UserRole;
use App\Models\Takmir;
use App\Models\Admin;
use App\Models\Mosque;
use App\Models\Organization;
use App\Models\JobdescOrg;

class TakmirController extends Controller
{

    public function index()
    {
        return view('dashboard.admin.user.takmir.all_user');        
    }

    
    public function create()
    {
        return view('dashboard.admin.user.takmir.add_user');
    }
    
    public function store(Request $request)
    {
        $user = new User;
        $takmir = new Takmir;
        $mosque = new Mosque;
        $org = new Organization;
        $jobdesc = new JobdescOrg;

        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required|unique:users',
            'password' => 'required|min:8'
        ]);
        
        $user->uuid = Uuid::uuid4();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

        switch ($request->role) {
            case 3:
                $takmir->user_id = $user->id;
                $takmir->save();

                $mosque->takmir_id = $takmir->id;
                $mosque->save();

                $org->takmir_id = $takmir->id;
                $org->save();

                $jobdesc->takmir_id = $takmir->id;
                $jobdesc->save();
                // dd($mosque);

                UserRole::create(['user_id' => $user->id,'role_id' => 3]);
                break;
            case 2:
                Admin::create(['user_id'=>$user->id]);
                UserRole::create(['user_id' => $user->id,'role_id' => 3]);
                UserRole::create(['user_id' => $user->id,'role_id' => 2]);
                break;
        }

        return redirect()->route('takmir.index')->with('success','Berhasil Menambahkan'); 
    }

    
    public function show($id)
    {
        $user = User::where('uuid',$id)->first();
        $takmir = $user->takmir()->first();
        $mosque = $takmir->mosque()->first();

        // dd($mosque);

        return view('dashboard.admin.user.takmir.detail_user',compact('user','takmir','mosque'));
    }
    
    public function edit($id)
    {
        $user = User::where('uuid',$id)->first();
        $takmir = $user->takmir()->first();
        $mosque = $takmir->mosque()->first();
        // dd($takmir);

        return view('dashboard.admin.user.takmir.edit_user',compact('user','takmir','mosque'));
    }
    
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|max:255|min:3',
            'email' => 'required',
            'password' => 'required|min:8'
        ]);
        
        $user = User::where('uuid',$id)->first();
        // dd($user);
        $takmir = $user->takmir()->first();
        $mosque = $takmir->mosque()->first();

        //============ User =========
        $user->name = $request->name;
        $user->email = $request->email;

        if ($request->password != $user->password) {
            $user->password = bcrypt($request->password);
        }
        $user->save();

        //=========== Takmir =============
        $takmir->province = $request->province;
        $takmir->address = $request->address;
        $takmir->hp = $request->hp;
        $takmir->birth_date = date('Y-m-d', strtotime($request->birth_date));
        $takmir->birth_place = $request->birth_place;
        $takmir->gender = $request->gender;

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/user',$photoName);
            $takmir->photo = $photoName;
        }
        $takmir->save();

        // ============ Mosque ===========
        $mosque->name = $request->mname;
        $mosque->province = $request->mprovince;
        $mosque->address = $request->maddress;
        $mosque->desc = $request->mdesc;

        if ($request->hasFile('mphoto')) {
            $photo = $request->file('mphoto');
            $photoName = $user->uuid.$photo->getClientOriginalName();
            $photo->storeAs('public/mosque',$photoName);
            $mosque->photo = $photoName;
        }

        $mosque->save();


        return redirect()->back()->with('success','Edit Success');
    }
    
    public function destroy($id)
    {
        $takmir = Takmir::find($id);
        
        $user = User::where('id',$takmir->user_id)->first();
        $user->delete();
    }

    public function takmirApi(){
        $user = DB::table('users')->rightJoin('takmirs','takmirs.user_id','=','users.id');

        return $this->displayTakmir($user);
    }
}

resources/views/dashboard/admin/user/admin/add_user.blade.php
@extends('dashboard.master')
@section('title')
Tambah Admin
@endsection
@section('content')
<div class="row">
    <div class="row flex-grow">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Tambah Admin</h4>
              <form class="forms-sample" method="POST" action="{{route('admin.store')}}" enctype="multipart/form-data">
                  {{csrf_field()}} {{ method_field('POST')}}
                <div class="form-group">
                    <label for="exampleInputEmail1">Nama</label>
                    <input required type="text" class="form-control" name="name" value="{{ old('name') }}" id="name" placeholder="Masukan Nama">
                    @error('name')
                      <span class="mt-1 alert-danger" role="alert">
                        <small>{{ $message }}</small>
                      </span>
                    @enderror
                </div>

                <div class="form-group">
                  <label for="exampleInputEmail1">Email address</label>
                  <input value="{{ old('email') }}" required type="email" class="form-control" name="email" id="email" placeholder="Masukan Email">
                  @error('email')
                      <span class="mt-1 alert-danger" role="alert">
                        <small>{{ $message }}</small>
                      </span>
                  @enderror
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input required type="password" class="form-control" id="password" name="password" placeholder="Password">
                  @error('password')
                      <span class="mt-1 alert-danger" role="alert">
                        <small>{{ $message }}</small>
                      </span>
                  @enderror
                </div>
                <button type="submit" class="btn btn-success mr-2">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/dashboard/admin/user/admin/all_user.blade.php
@extends('dashboard.master')
@section('title')
Semua Admin
@endsection
@section('content')
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                @include('layouts.patrials.alerts')
                <div class="row">
                    <div class="col-md-6"><h4 class="card-title"> Semua Admin </h4></div>
                    <div class="col-md-6"><a class="btn btn-success float-right" href="{{route('admin.create')}}">Tambah Admin</a></div>
                </div>
                <div class="center-pos" id="loadingDiv">
                        <img class="loading" src="{{asset('img/loading.gif')}}">
                </div>
                <div class="table-responsive">
                    <table id="table-admin" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Nama</th>
                                <th>Telepon</th>
                                <th>Gender</th>
                                <th>Provinsi</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script type="text/javascript">
    
    var ajaxApi = '{{route("api.admin")}}'
    var table = $('#table-admin').DataTable({
        order: [[1,'desc']],
        processing: true,
        serverSide: true,
        ajax : ajaxApi,
        columns : [
            {data: 'name', name: 'name'},
            {data: 'hp', name: 'hp'},
            {data: 'gender', name: 'gender'},
            {data: 'province', name: 'province'},
            {data: 'action', name: 'action',ordertable: false, searchable:false},
        ]

    })
    

    // Delete Data
    function deleteUser(id){
        // alert('bismillah');
        
        var csrf_token = $('meta[name="csrf-token"]').attr('content');

        Swal.fire({
          title: 'Kamu yakin ?',
          text: "User yang di hapus tidak akan kembali!",
          type: 'warning',
          showCancelButton: true,
          cancelButtonColor: '#d33',
          confirmButtonColor: '#3085d6',
          confirmButtonText: 'Ya, Hapus ini!'
        }).then((result) => {
        if (result.value) {
          $.ajax({
            url: "{{ url('admin') }}" + '/' + id,
            type: "DELETE",
            data: {'_method' : 'DELETE', '_token' : csrf_token},
            success: function(data){
              table.ajax.reload();
              swal({
                title:'Berhasil',
                text: 'User Sudah di hapus',
                type: 'success',
                timer: '1500'
              })
            },
            error: function(){
              swal({
                title: 'Oops',
                text: 'Something went wrong',
                type: 'error',
                timer: '1500'
              })
            }
          })
        }
      })
    }

    
    </script>
@endsection

resources/views/dashboard/admin/user/admin/detail_user.blade.php
@extends('dashboard.master')
@section('title')
Info Admin
@endsection
@section('content')
<div class="row">
  @include('layouts.patrials.alerts')
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <h5 class="">Info Admin</h5>
        </div>
        <div class="">
          <div class="row">
            <div class="col-md-3 col-lg-3 " align="center">
              @if (strlen($admin->photo) != 0)
              <img alt="User Pic" src="{{asset('storage/user/'.$admin->photo)}}" class="img-circle img-responsive img-thumbnail">         
              @else
              <img alt="User Pic" src="{{asset('img/user.png')}}" class="img-circle img-responsive img-thumbnail"> 
              @endif
              
            </div>
            <div class="table-responsive col-md-9 col-lg-9 ">
              <table class="table table-striped table-hover">
                <tbody>
                  <tr>
                    <td><b>Nama </b></td>
                    <td>{{$user->name}}</td>
                  </tr>
                  <tr>
                    <td><b>Tempat, Tanggal Lahir</b></td>
                    <td>{{$admin->birth_date}} , {{$admin->birth_place}}</td>
                  </tr>
                  <tr>
                    <td><b>Jenis Kelamin</b></td>
                    <td>{{$admin->gender}}</td>
                  </tr>
                  <tr>
                    <td><b>Provinsi</b></td>
                    <td>{{$admin->province}}</td>
                  </tr>
                  <tr>
                    <td><b>Alamat</b></td>
                    <td>{{$admin->address}}</td>
                  </tr>
                  <tr>
                    <td><b>Email</b></td>
                    <td><a href="{{$user->email}}">{{$user->email}}</a></td>
                  </tr>
                  <tr>
                    <td><b>Nomor HandPhone</b></td>
                    <td>{{$admin->hp}}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection